version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      target: development
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    command: npm run start
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge